name: External Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  
  build:
    if: always() && github.event_name != 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
